# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: 
  python:latest  # this sets default image for jobs

semgrep-sast:
  stage: test
  script:
    - echo "Executando SAST com Semgrep..."
    - semgrep --config auto --output gl-sast-report.json
    - ls -la # Verifica se o arquivo foi criado
  artifacts:
    paths:
      - gl-sast-report.json
    expire_in: 1 day

check-sast-report:
  stage: test
  script:
    - echo "Listando arquivos disponíveis:"
    - ls -la
    - echo "Validando o relatório SAST..."
    - |
      python -c "
      import json
      with open('gl-sast-report.json') as f:
          report = json.load(f)
      vulnerabilities = report.get('vulnerabilities', [])
      if vulnerabilities:
          print(f'Found {len(vulnerabilities)} vulnerabilities:')
          for vuln in vulnerabilities:
              print(f'- {vuln.get(\"message\", \"No message\")}')
          exit(1)
      else:
          print('No vulnerabilities found.')
      "
  dependencies:
    - semgrep-sast
  allow_failure: false

include:
- template: Security/SAST.gitlab-ci.yml